// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kratos-admin/app/admin/service/internal/data/ent/notificationmessagerecipient"
	"kratos-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationMessageRecipientUpdate is the builder for updating NotificationMessageRecipient entities.
type NotificationMessageRecipientUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationMessageRecipientMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationMessageRecipientUpdate builder.
func (_u *NotificationMessageRecipientUpdate) Where(ps ...predicate.NotificationMessageRecipient) *NotificationMessageRecipientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationMessageRecipientUpdate) SetUpdatedAt(v time.Time) *NotificationMessageRecipientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdate) SetNillableUpdatedAt(v *time.Time) *NotificationMessageRecipientUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *NotificationMessageRecipientUpdate) ClearUpdatedAt() *NotificationMessageRecipientUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NotificationMessageRecipientUpdate) SetDeletedAt(v time.Time) *NotificationMessageRecipientUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdate) SetNillableDeletedAt(v *time.Time) *NotificationMessageRecipientUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NotificationMessageRecipientUpdate) ClearDeletedAt() *NotificationMessageRecipientUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *NotificationMessageRecipientUpdate) SetMessageID(v uint32) *NotificationMessageRecipientUpdate {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdate) SetNillableMessageID(v *uint32) *NotificationMessageRecipientUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *NotificationMessageRecipientUpdate) AddMessageID(v int32) *NotificationMessageRecipientUpdate {
	_u.mutation.AddMessageID(v)
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *NotificationMessageRecipientUpdate) ClearMessageID() *NotificationMessageRecipientUpdate {
	_u.mutation.ClearMessageID()
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *NotificationMessageRecipientUpdate) SetRecipientID(v uint32) *NotificationMessageRecipientUpdate {
	_u.mutation.ResetRecipientID()
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdate) SetNillableRecipientID(v *uint32) *NotificationMessageRecipientUpdate {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// AddRecipientID adds value to the "recipient_id" field.
func (_u *NotificationMessageRecipientUpdate) AddRecipientID(v int32) *NotificationMessageRecipientUpdate {
	_u.mutation.AddRecipientID(v)
	return _u
}

// ClearRecipientID clears the value of the "recipient_id" field.
func (_u *NotificationMessageRecipientUpdate) ClearRecipientID() *NotificationMessageRecipientUpdate {
	_u.mutation.ClearRecipientID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationMessageRecipientUpdate) SetStatus(v notificationmessagerecipient.Status) *NotificationMessageRecipientUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdate) SetNillableStatus(v *notificationmessagerecipient.Status) *NotificationMessageRecipientUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *NotificationMessageRecipientUpdate) ClearStatus() *NotificationMessageRecipientUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// Mutation returns the NotificationMessageRecipientMutation object of the builder.
func (_u *NotificationMessageRecipientUpdate) Mutation() *NotificationMessageRecipientMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationMessageRecipientUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationMessageRecipientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationMessageRecipientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationMessageRecipientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationMessageRecipientUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := notificationmessagerecipient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NotificationMessageRecipient.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotificationMessageRecipientUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationMessageRecipientUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotificationMessageRecipientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationmessagerecipient.Table, notificationmessagerecipient.Columns, sqlgraph.NewFieldSpec(notificationmessagerecipient.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationmessagerecipient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(notificationmessagerecipient.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(notificationmessagerecipient.FieldMessageID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(notificationmessagerecipient.FieldMessageID, field.TypeUint32, value)
	}
	if _u.mutation.MessageIDCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldMessageID, field.TypeUint32)
	}
	if value, ok := _u.mutation.RecipientID(); ok {
		_spec.SetField(notificationmessagerecipient.FieldRecipientID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRecipientID(); ok {
		_spec.AddField(notificationmessagerecipient.FieldRecipientID, field.TypeUint32, value)
	}
	if _u.mutation.RecipientIDCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldRecipientID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notificationmessagerecipient.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldStatus, field.TypeEnum)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationmessagerecipient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationMessageRecipientUpdateOne is the builder for updating a single NotificationMessageRecipient entity.
type NotificationMessageRecipientUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationMessageRecipientMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationMessageRecipientUpdateOne) SetUpdatedAt(v time.Time) *NotificationMessageRecipientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdateOne) SetNillableUpdatedAt(v *time.Time) *NotificationMessageRecipientUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *NotificationMessageRecipientUpdateOne) ClearUpdatedAt() *NotificationMessageRecipientUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NotificationMessageRecipientUpdateOne) SetDeletedAt(v time.Time) *NotificationMessageRecipientUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdateOne) SetNillableDeletedAt(v *time.Time) *NotificationMessageRecipientUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NotificationMessageRecipientUpdateOne) ClearDeletedAt() *NotificationMessageRecipientUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *NotificationMessageRecipientUpdateOne) SetMessageID(v uint32) *NotificationMessageRecipientUpdateOne {
	_u.mutation.ResetMessageID()
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdateOne) SetNillableMessageID(v *uint32) *NotificationMessageRecipientUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// AddMessageID adds value to the "message_id" field.
func (_u *NotificationMessageRecipientUpdateOne) AddMessageID(v int32) *NotificationMessageRecipientUpdateOne {
	_u.mutation.AddMessageID(v)
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *NotificationMessageRecipientUpdateOne) ClearMessageID() *NotificationMessageRecipientUpdateOne {
	_u.mutation.ClearMessageID()
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *NotificationMessageRecipientUpdateOne) SetRecipientID(v uint32) *NotificationMessageRecipientUpdateOne {
	_u.mutation.ResetRecipientID()
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdateOne) SetNillableRecipientID(v *uint32) *NotificationMessageRecipientUpdateOne {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// AddRecipientID adds value to the "recipient_id" field.
func (_u *NotificationMessageRecipientUpdateOne) AddRecipientID(v int32) *NotificationMessageRecipientUpdateOne {
	_u.mutation.AddRecipientID(v)
	return _u
}

// ClearRecipientID clears the value of the "recipient_id" field.
func (_u *NotificationMessageRecipientUpdateOne) ClearRecipientID() *NotificationMessageRecipientUpdateOne {
	_u.mutation.ClearRecipientID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationMessageRecipientUpdateOne) SetStatus(v notificationmessagerecipient.Status) *NotificationMessageRecipientUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationMessageRecipientUpdateOne) SetNillableStatus(v *notificationmessagerecipient.Status) *NotificationMessageRecipientUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *NotificationMessageRecipientUpdateOne) ClearStatus() *NotificationMessageRecipientUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// Mutation returns the NotificationMessageRecipientMutation object of the builder.
func (_u *NotificationMessageRecipientUpdateOne) Mutation() *NotificationMessageRecipientMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationMessageRecipientUpdate builder.
func (_u *NotificationMessageRecipientUpdateOne) Where(ps ...predicate.NotificationMessageRecipient) *NotificationMessageRecipientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationMessageRecipientUpdateOne) Select(field string, fields ...string) *NotificationMessageRecipientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationMessageRecipient entity.
func (_u *NotificationMessageRecipientUpdateOne) Save(ctx context.Context) (*NotificationMessageRecipient, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationMessageRecipientUpdateOne) SaveX(ctx context.Context) *NotificationMessageRecipient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationMessageRecipientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationMessageRecipientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationMessageRecipientUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := notificationmessagerecipient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NotificationMessageRecipient.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotificationMessageRecipientUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationMessageRecipientUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotificationMessageRecipientUpdateOne) sqlSave(ctx context.Context) (_node *NotificationMessageRecipient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationmessagerecipient.Table, notificationmessagerecipient.Columns, sqlgraph.NewFieldSpec(notificationmessagerecipient.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationMessageRecipient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationmessagerecipient.FieldID)
		for _, f := range fields {
			if !notificationmessagerecipient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationmessagerecipient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationmessagerecipient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(notificationmessagerecipient.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(notificationmessagerecipient.FieldMessageID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedMessageID(); ok {
		_spec.AddField(notificationmessagerecipient.FieldMessageID, field.TypeUint32, value)
	}
	if _u.mutation.MessageIDCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldMessageID, field.TypeUint32)
	}
	if value, ok := _u.mutation.RecipientID(); ok {
		_spec.SetField(notificationmessagerecipient.FieldRecipientID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRecipientID(); ok {
		_spec.AddField(notificationmessagerecipient.FieldRecipientID, field.TypeUint32, value)
	}
	if _u.mutation.RecipientIDCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldRecipientID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notificationmessagerecipient.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(notificationmessagerecipient.FieldStatus, field.TypeEnum)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &NotificationMessageRecipient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationmessagerecipient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
