// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kratos-admin/app/admin/service/internal/data/ent/predicate"
	"kratos-admin/app/admin/service/internal/data/ent/userposition"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPositionUpdate is the builder for updating UserPosition entities.
type UserPositionUpdate struct {
	config
	hooks     []Hook
	mutation  *UserPositionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserPositionUpdate builder.
func (_u *UserPositionUpdate) Where(ps ...predicate.UserPosition) *UserPositionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserPositionUpdate) SetUpdateTime(v time.Time) *UserPositionUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *UserPositionUpdate) SetNillableUpdateTime(v *time.Time) *UserPositionUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *UserPositionUpdate) ClearUpdateTime() *UserPositionUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *UserPositionUpdate) SetDeleteTime(v time.Time) *UserPositionUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *UserPositionUpdate) SetNillableDeleteTime(v *time.Time) *UserPositionUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *UserPositionUpdate) ClearDeleteTime() *UserPositionUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *UserPositionUpdate) SetCreateBy(v uint32) *UserPositionUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *UserPositionUpdate) SetNillableCreateBy(v *uint32) *UserPositionUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *UserPositionUpdate) AddCreateBy(v int32) *UserPositionUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *UserPositionUpdate) ClearCreateBy() *UserPositionUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserPositionUpdate) SetUserID(v uint32) *UserPositionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserPositionUpdate) SetNillableUserID(v *uint32) *UserPositionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserPositionUpdate) AddUserID(v int32) *UserPositionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPositionID sets the "position_id" field.
func (_u *UserPositionUpdate) SetPositionID(v uint32) *UserPositionUpdate {
	_u.mutation.ResetPositionID()
	_u.mutation.SetPositionID(v)
	return _u
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (_u *UserPositionUpdate) SetNillablePositionID(v *uint32) *UserPositionUpdate {
	if v != nil {
		_u.SetPositionID(*v)
	}
	return _u
}

// AddPositionID adds value to the "position_id" field.
func (_u *UserPositionUpdate) AddPositionID(v int32) *UserPositionUpdate {
	_u.mutation.AddPositionID(v)
	return _u
}

// Mutation returns the UserPositionMutation object of the builder.
func (_u *UserPositionUpdate) Mutation() *UserPositionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserPositionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPositionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserPositionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPositionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserPositionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserPositionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserPositionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userposition.Table, userposition.Columns, sqlgraph.NewFieldSpec(userposition.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(userposition.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userposition.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(userposition.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(userposition.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(userposition.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(userposition.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(userposition.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(userposition.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userposition.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userposition.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.PositionID(); ok {
		_spec.SetField(userposition.FieldPositionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPositionID(); ok {
		_spec.AddField(userposition.FieldPositionID, field.TypeUint32, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userposition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserPositionUpdateOne is the builder for updating a single UserPosition entity.
type UserPositionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserPositionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserPositionUpdateOne) SetUpdateTime(v time.Time) *UserPositionUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *UserPositionUpdateOne) SetNillableUpdateTime(v *time.Time) *UserPositionUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *UserPositionUpdateOne) ClearUpdateTime() *UserPositionUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *UserPositionUpdateOne) SetDeleteTime(v time.Time) *UserPositionUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *UserPositionUpdateOne) SetNillableDeleteTime(v *time.Time) *UserPositionUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *UserPositionUpdateOne) ClearDeleteTime() *UserPositionUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *UserPositionUpdateOne) SetCreateBy(v uint32) *UserPositionUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *UserPositionUpdateOne) SetNillableCreateBy(v *uint32) *UserPositionUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *UserPositionUpdateOne) AddCreateBy(v int32) *UserPositionUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *UserPositionUpdateOne) ClearCreateBy() *UserPositionUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserPositionUpdateOne) SetUserID(v uint32) *UserPositionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserPositionUpdateOne) SetNillableUserID(v *uint32) *UserPositionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserPositionUpdateOne) AddUserID(v int32) *UserPositionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPositionID sets the "position_id" field.
func (_u *UserPositionUpdateOne) SetPositionID(v uint32) *UserPositionUpdateOne {
	_u.mutation.ResetPositionID()
	_u.mutation.SetPositionID(v)
	return _u
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (_u *UserPositionUpdateOne) SetNillablePositionID(v *uint32) *UserPositionUpdateOne {
	if v != nil {
		_u.SetPositionID(*v)
	}
	return _u
}

// AddPositionID adds value to the "position_id" field.
func (_u *UserPositionUpdateOne) AddPositionID(v int32) *UserPositionUpdateOne {
	_u.mutation.AddPositionID(v)
	return _u
}

// Mutation returns the UserPositionMutation object of the builder.
func (_u *UserPositionUpdateOne) Mutation() *UserPositionMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserPositionUpdate builder.
func (_u *UserPositionUpdateOne) Where(ps ...predicate.UserPosition) *UserPositionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserPositionUpdateOne) Select(field string, fields ...string) *UserPositionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserPosition entity.
func (_u *UserPositionUpdateOne) Save(ctx context.Context) (*UserPosition, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPositionUpdateOne) SaveX(ctx context.Context) *UserPosition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserPositionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPositionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserPositionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserPositionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserPositionUpdateOne) sqlSave(ctx context.Context) (_node *UserPosition, err error) {
	_spec := sqlgraph.NewUpdateSpec(userposition.Table, userposition.Columns, sqlgraph.NewFieldSpec(userposition.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserPosition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userposition.FieldID)
		for _, f := range fields {
			if !userposition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userposition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(userposition.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userposition.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(userposition.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(userposition.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(userposition.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(userposition.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(userposition.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(userposition.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userposition.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userposition.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.PositionID(); ok {
		_spec.SetField(userposition.FieldPositionID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPositionID(); ok {
		_spec.AddField(userposition.FieldPositionID, field.TypeUint32, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserPosition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userposition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
