// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: admin/service/v1/i_admin_login_log.proto

/* eslint-disable */
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";
import {
  type AdminLoginLog,
  type GetAdminLoginLogRequest,
  type ListAdminLoginLogResponse,
} from "../../../system/service/v1/admin_login_log.pb";

/** 后台登录日志管理服务 */
export interface AdminLoginLogService {
  /** 查询后台登录日志列表 */
  List(request: PagingRequest): Promise<ListAdminLoginLogResponse>;
  /** 查询后台登录日志详情 */
  Get(request: GetAdminLoginLogRequest): Promise<AdminLoginLog>;
}
