// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: admin/service/v1/i_admin_operation_log.proto

/* eslint-disable */
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";
import {
  type AdminOperationLog,
  type GetAdminOperationLogRequest,
  type ListAdminOperationLogResponse,
} from "../../../system/service/v1/admin_operation_log.pb";

/** 后台操作日志管理服务 */
export interface AdminOperationLogService {
  /** 查询后台操作日志列表 */
  ListAdminOperationLog(request: PagingRequest): Promise<ListAdminOperationLogResponse>;
  /** 查询后台操作日志详情 */
  GetAdminOperationLog(request: GetAdminOperationLogRequest): Promise<AdminOperationLog>;
}
