// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: admin/service/v1/i_api_resource.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type Timestamp } from "../../../google/protobuf/timestamp.pb";
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";

/** API资源 */
export interface ApiResource {
  /** 资源ID */
  id?:
    | number
    | null
    | undefined;
  /** 所属业务模块 */
  module?:
    | string
    | null
    | undefined;
  /** 描述 */
  description?:
    | string
    | null
    | undefined;
  /** 接口操作名 */
  operation?:
    | string
    | null
    | undefined;
  /** 接口路径 */
  path?:
    | string
    | null
    | undefined;
  /** 请求方法 */
  method?:
    | string
    | null
    | undefined;
  /** 创建者ID */
  createBy?:
    | number
    | null
    | undefined;
  /** 更新者ID */
  updateBy?:
    | number
    | null
    | undefined;
  /** 创建时间 */
  createTime?:
    | Timestamp
    | null
    | undefined;
  /** 更新时间 */
  updateTime?:
    | Timestamp
    | null
    | undefined;
  /** 删除时间 */
  deleteTime?: Timestamp | null | undefined;
}

/** 查询列表 - 回应 */
export interface ListApiResourceResponse {
  items: ApiResource[];
  total: number;
}

/** 查询 - 请求 */
export interface GetApiResourceRequest {
  id: number;
}

/** 创建 - 请求 */
export interface CreateApiResourceRequest {
  data: ApiResource | null;
}

/** 更新 - 请求 */
export interface UpdateApiResourceRequest {
  data:
    | ApiResource
    | null;
  /** 要更新的字段列表 */
  updateMask:
    | string[]
    | null;
  /** 如果设置为true的时候，资源不存在则会新增(插入)，并且在这种情况下`updateMask`字段将会被忽略。 */
  allowMissing?: boolean | null | undefined;
}

/** 删除 - 请求 */
export interface DeleteApiResourceRequest {
  id: number;
}

/** API资源管理服务 */
export interface ApiResourceService {
  /** 查询列表 */
  List(request: PagingRequest): Promise<ListApiResourceResponse>;
  /** 查询详情 */
  Get(request: GetApiResourceRequest): Promise<ApiResource>;
  /** 创建 */
  Create(request: CreateApiResourceRequest): Promise<Empty>;
  /** 更新 */
  Update(request: UpdateApiResourceRequest): Promise<Empty>;
  /** 删除 */
  Delete(request: DeleteApiResourceRequest): Promise<Empty>;
  /** 同步API资源 */
  SyncApiResources(request: Empty): Promise<Empty>;
  GetWalkRouteData(request: Empty): Promise<ListApiResourceResponse>;
}
