// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: admin/service/v1/i_authentication.proto

/* eslint-disable */
import {
  type GetMeRequest,
  type LoginRequest,
  type LoginResponse,
  type LogoutRequest,
} from "../../../authentication/service/v1/authentication.pb";
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type User } from "../../../user/service/v1/user.pb";

/** 用户后台登录认证服务 */
export interface AuthenticationService {
  /** 登录 */
  Login(request: LoginRequest): Promise<LoginResponse>;
  /** 登出 */
  Logout(request: LogoutRequest): Promise<Empty>;
  /** 刷新认证令牌 */
  RefreshToken(request: LoginRequest): Promise<LoginResponse>;
  /** 后台获取已经登录的用户的数据 */
  GetMe(request: GetMeRequest): Promise<User>;
}
