// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: admin/service/v1/i_notification_message_recipient.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import {
  type CreateNotificationMessageRecipientRequest,
  type DeleteNotificationMessageRecipientRequest,
  type GetNotificationMessageRecipientRequest,
  type ListNotificationMessageRecipientResponse,
  type NotificationMessageRecipient,
  type UpdateNotificationMessageRecipientRequest,
} from "../../../internal_message/service/v1/notification_message_recipient.pb";
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";

/** 通知消息接收者管理服务 */
export interface NotificationMessageRecipientService {
  /** 查询通知消息接收者列表 */
  ListNotificationMessageRecipient(request: PagingRequest): Promise<ListNotificationMessageRecipientResponse>;
  /** 查询通知消息接收者详情 */
  GetNotificationMessageRecipient(
    request: GetNotificationMessageRecipientRequest,
  ): Promise<NotificationMessageRecipient>;
  /** 创建通知消息接收者 */
  CreateNotificationMessageRecipient(request: CreateNotificationMessageRecipientRequest): Promise<Empty>;
  /** 更新通知消息接收者 */
  UpdateNotificationMessageRecipient(request: UpdateNotificationMessageRecipientRequest): Promise<Empty>;
  /** 删除通知消息接收者 */
  DeleteNotificationMessageRecipient(request: DeleteNotificationMessageRecipientRequest): Promise<Empty>;
}
