// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               unknown
// source: admin/service/v1/i_user_profile.proto

/* eslint-disable */
import type { Empty } from "../../../google/protobuf/empty.pb";
import type { UpdateUserRequest, User } from "../../../user/service/v1/user.pb";

/** 用户个人资料服务 */
export interface UserProfileService {
  /** 获取用户资料 */
  GetUser(request: Empty): Promise<User>;
  /** 更新用户资料 */
  UpdateUser(request: UpdateUserRequest): Promise<Empty>;
}
