// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               unknown
// source: file/service/v1/file.proto

/* eslint-disable */
import { type Empty } from "../../../google/protobuf/empty.pb";
import { type Timestamp } from "../../../google/protobuf/timestamp.pb";
import { type PagingRequest } from "../../../pagination/v1/pagination.pb";

/** OSS供应商 */
export enum OSSProvider {
  MinIO = "MinIO",
  Aliyun = "Aliyun",
  AWS = "AWS",
  Azure = "Azure",
  Baidu = "Baidu",
  Qiniu = "Qiniu",
  Tencent = "Tencent",
  Google = "Google",
  Huawei = "Huawei",
  QCloud = "QCloud",
  Local = "Local",
}

/** 文件 */
export interface File {
  /** 文件ID */
  id?:
    | number
    | null
    | undefined;
  /** OSS供应商 */
  provider?:
    | OSSProvider
    | null
    | undefined;
  /** 存储桶名称 */
  bucketName?:
    | string
    | null
    | undefined;
  /** 文件目录 */
  fileDirectory?:
    | string
    | null
    | undefined;
  /** 文件Guid */
  fileGuid?:
    | string
    | null
    | undefined;
  /** 保存文件名 */
  saveFileName?:
    | string
    | null
    | undefined;
  /** 文件名 */
  fileName?:
    | string
    | null
    | undefined;
  /** 文件扩展名 */
  extension?:
    | string
    | null
    | undefined;
  /** 文件字节长度 */
  size?:
    | string
    | null
    | undefined;
  /** 文件大小格式化 */
  sizeFormat?:
    | string
    | null
    | undefined;
  /** 链接地址 */
  linkUrl?:
    | string
    | null
    | undefined;
  /** md5码，防止上传重复文件 */
  md5?:
    | string
    | null
    | undefined;
  /** 创建时间 */
  createTime?:
    | Timestamp
    | null
    | undefined;
  /** 更新时间 */
  updateTime?:
    | Timestamp
    | null
    | undefined;
  /** 删除时间 */
  deleteTime?: Timestamp | null | undefined;
}

/** 文件列表 - 回应 */
export interface ListFileResponse {
  items: File[];
  total: number;
}

/** 文件数据 - 请求 */
export interface GetFileRequest {
  id: number;
}

/** 创建文件 - 请求 */
export interface CreateFileRequest {
  data:
    | File
    | null;
  /** 操作用户ID */
  operatorId?: number | null | undefined;
}

/** 更新文件 - 请求 */
export interface UpdateFileRequest {
  /** 操作用户ID */
  operatorId?: number | null | undefined;
  data:
    | File
    | null;
  /** 要更新的字段列表 */
  updateMask:
    | string[]
    | null;
  /** 如果设置为true的时候，资源不存在则会新增(插入)，并且在这种情况下`updateMask`字段将会被忽略。 */
  allowMissing?: boolean | null | undefined;
}

/** 删除文件 - 请求 */
export interface DeleteFileRequest {
  id: number;
  /** 操作用户ID */
  operatorId?: number | null | undefined;
}

/** 文件服务 */
export interface FileService {
  /** 获取文件列表 */
  ListFile(request: PagingRequest): Promise<ListFileResponse>;
  /** 获取文件数据 */
  GetFile(request: GetFileRequest): Promise<File>;
  /** 创建文件 */
  CreateFile(request: CreateFileRequest): Promise<Empty>;
  /** 更新文件 */
  UpdateFile(request: UpdateFileRequest): Promise<Empty>;
  /** 删除文件 */
  DeleteFile(request: DeleteFileRequest): Promise<Empty>;
}
