// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminLoginLog is the predicate function for adminloginlog builders.
type AdminLoginLog func(*sql.Selector)

// AdminOperationLog is the predicate function for adminoperationlog builders.
type AdminOperationLog func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Dict is the predicate function for dict builders.
type Dict func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
