// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminLoginLog is the predicate function for adminloginlog builders.
type AdminLoginLog func(*sql.Selector)

// AdminLoginRestriction is the predicate function for adminloginrestriction builders.
type AdminLoginRestriction func(*sql.Selector)

// AdminOperationLog is the predicate function for adminoperationlog builders.
type AdminOperationLog func(*sql.Selector)

// ApiResource is the predicate function for apiresource builders.
type ApiResource func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// DictEntry is the predicate function for dictentry builders.
type DictEntry func(*sql.Selector)

// DictType is the predicate function for dicttype builders.
type DictType func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// InternalMessage is the predicate function for internalmessage builders.
type InternalMessage func(*sql.Selector)

// InternalMessageCategory is the predicate function for internalmessagecategory builders.
type InternalMessageCategory func(*sql.Selector)

// InternalMessageRecipient is the predicate function for internalmessagerecipient builders.
type InternalMessageRecipient func(*sql.Selector)

// Language is the predicate function for language builders.
type Language func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleApi is the predicate function for roleapi builders.
type RoleApi func(*sql.Selector)

// RoleDept is the predicate function for roledept builders.
type RoleDept func(*sql.Selector)

// RoleMenu is the predicate function for rolemenu builders.
type RoleMenu func(*sql.Selector)

// RoleOrg is the predicate function for roleorg builders.
type RoleOrg func(*sql.Selector)

// RolePosition is the predicate function for roleposition builders.
type RolePosition func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserCredential is the predicate function for usercredential builders.
type UserCredential func(*sql.Selector)

// UserPosition is the predicate function for userposition builders.
type UserPosition func(*sql.Selector)

// UserRole is the predicate function for userrole builders.
type UserRole func(*sql.Selector)
